// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tokqczjznpnqnugnjopg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRva3Fjemp6bnBucW51Z25qb3BnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MDAxMjEsImV4cCI6MjA3Mjk3NjEyMX0.p2C8a5inisa4wpl9BSnRySEPfjjC_cIxM2Y_OD_h31w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});